version: '3'

services:
  web:
    build: ./web
    image: nimble/web
    command: bash -c "yarn build && yarn dev"
    volumes:
      - "./web/__mocks__:/usr/src/app/__mocks__"
      - "./web/__tests__:/usr/src/app/__tests__"
      - "./web/components:/usr/src/app/components"
      - "./web/contexts:/usr/src/app/contexts"
      - "./web/pages:/usr/src/app/pages"
      - "./web/services:/usr/src/app/services"
      - "./web/static:/usr/src/app/static"
      - "./web/styles:/usr/src/app/styles"
      - "./web/utils:/usr/src/app/utils"
      - "./web/config.js:/usr/src/app/config.js"
      - "./web/i18n.js:/usr/src/app/i18n.js"
    environment:
      NODE_ENV: 'development'
      PORT: 3000
      ASSET_PREFIX: ''
      FIREBASE_API_KEY: 'AIzaSyCV-lag3MM6jHZRYuKh3PcP5B63cPYeazE'
      FIREBASE_AUTH_DOMAIN: 'nimble-challenge-cc890.firebaseapp.com'
      FIREBASE_PROJECT: 'nimble-challenge-cc890'
      AXIOS_TIMEOUT: 5000
      API_DOMAIN: 'http://localhost:3001/api'
    ports:
      - "3000:3000"
  db:
    image: postgres:9.6
    volumes:
      - "postgres-db:/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: "api"
      POSTGRES_PASSWORD: "api"
      POSTGRES_DB: "api"
  api:
    build: ./api
    image: nimble/api
    command: >
      bash -c "((bundle check >/dev/null 2>&1) || bundle install) && (
        ($$(($$(ls -1 ./node_modules | wc -l) >= 10)) >/dev/null 2>&1) ||
        yarn install
      ) &&
      rm -f tmp/pids/server.pid &&
      rails s -b '0.0.0.0'"
    volumes:
      - "./api:/usr/src/app"
    ports:
      - "3001:3000"
    environment:
      FIREBASE_AUD: nimble-challenge-cc890
      FIREBASE_ISS: https://securetoken.google.com/nimble-challenge-cc890
    depends_on:
      - db
volumes:
  postgres-db:
